apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
spec:
  schedule: "*/{{ .Values.interval }} * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ .Chart.Name }}"
              image: "zerodayyy/kleaner:{{ .Chart.AppVersion }}"
              args:
                {{- if .Values.debug }}
                - "--debug"
                {{- end }}
                {{- if .Values.namespaces }}
                - "--namespaces"
                - {{ join "," .Values.namespaces | quote }}
                {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ .Chart.Name }}
